train_data_path: data/processed/train_clean.csv
test_data_path: data/processed/test_clean.csv
model_output_path: submissions/submission.csv

model:
  name: xgboost
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100

metrics:
  - weighted_mae
